[target.loongarch64-unknown-linux-gnu]
image = "ghcr.io/cross-rs/loongarch64-unknown-linux-gnu:edge"
[target.loongarch64-unknown-linux-musl]
image = "ghcr.io/cross-rs/loongarch64-unknown-linux-musl:edge"
[target.aarch64-unknown-freebsd]
build-std = true
image = "ghcr.io/cross-rs/aarch64-unknown-freebsd:edge"
